# Generated by Django 5.1.4 on 2025-02-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='groups',
            field=models.ManyToManyField(to='attendance.group'),
        ),
    ]
